[package]
name = "coding_assessment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
web3 = "0.18.0"
tokio = { version = "1.24.1", features = ["full"] }
hex-literal = "0.3"
env_logger = "0.10.0"
 
